NUMPY: It works on N-darray(N-directional array). 

In [1]:
import numpy as np

### np.array

In [2]:
l = [1,2,3,5]
ndarray_1d = np.array(l) #creating a vectorized 1d array using np.array
print(type(ndarray_1d))

<class 'numpy.ndarray'>


### Adding to each value of an array without iterations

In [3]:
print(ndarray_1d)
ndarray_1d = ndarray_1d + 2 #adding 2 to each value of the array
print(ndarray_1d)
# we cannot extend the length of the ndarray unlike lists.

[1 2 3 5]
[3 4 5 7]


### Converting the array back to python lists

In [4]:
array_to_list = ndarray_1d.tolist()
print(type(array_to_list))
print(array_to_list)

<class 'list'>
[3, 4, 5, 7]


### Extracting info about an already created array - no of rows,cols datatype, dimensions, size

In [5]:
list_of_lists = [[1,1,1,1],[2,2,2,2],[1,2,3,4]]
nd_2darray = np.array(list_of_lists)
# now of rows and columns through --- SHAPE
print(nd_2darray.shape)
# datatype --- DTYPE
print(nd_2darray.dtype)
# no of dimensions --- NDIM
print(nd_2darray.ndim)
# size of the array --- SIZE
print(nd_2darray.size)

(3, 4)
int32
2
12


### Extracting items from arrays

In [6]:
print(nd_2darray[1:,1]) #1st row onwards(:) and 1 column element

[2 2]


### BOOLEAN INDEXING 

In [7]:
nd_2darray_bool = nd_2darray == 1 ##using comparison operations. Result in form of boolean.
print(nd_2darray_bool)

[[ True  True  True  True]
 [False False False False]
 [ True False False False]]


###  Reversing the rows, cols or both

In [8]:
reverse_array_rows = nd_2darray[::-1,] #reversing only the rows
print(reverse_array_rows)
print("")
reverse_array_rows_and_cols = nd_2darray[::-1,::-1]
print(reverse_array_rows_and_cols) #reversing both rows and cols

[[1 2 3 4]
 [2 2 2 2]
 [1 1 1 1]]

[[4 3 2 1]
 [2 2 2 2]
 [1 1 1 1]]


### Representing Not a number(NaN) and infinite values
and
### Converting nan and inf back to a value

In [9]:
l4 = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(l4, dtype = "float")
arr2[1][1] = np.nan #specifying not a number
arr2[1][2] = np.inf #specifying infinite value
print(arr2)

missing_value_bool = np.isnan(arr2) | np.isinf(arr2) ## use ISNAN and ISINF
arr2[missing_value_bool] = -1
print(arr2)

[[ 1.  2.  3.]
 [ 4. nan inf]
 [ 7.  8.  9.]]
[[ 1.  2.  3.]
 [ 4. -1. -1.]
 [ 7.  8.  9.]]


### computing mean, min, max of the entire matrix, of a particular row/column, cumilative sum

In [10]:
###### Of the entire matrix
mean = arr2.mean()
print(mean)
min = arr2.min()
print(min)
max = arr2.max()
print(max)

###### Of a particular row or column
mean_of_row = np.amin(arr2, axis = 1)
print(mean_of_row)

############# Cumilative sum
cum_sum = np.cumsum(arr2)

####
### np.apply_over_axis ----> later on

3.5555555555555554
-1.0
9.0
[ 1. -1.  7.]


### Creating new arrays from the existing arrays

In [11]:
new_arr2 = arr2[1:,1:].copy() ## v.imp to copy otherwise will reflect changes in the main array as well
new_arr2[1][1] = 100
print(new_arr2)
print(arr2)

[[ -1.  -1.]
 [  8. 100.]]
[[ 1.  2.  3.]
 [ 4. -1. -1.]
 [ 7.  8.  9.]]


### Reshaping and Flattening 2d arrays - Reshape, flatten and ravel

In [12]:
l5 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
arr3 = np.array(l5) 
print(arr3.reshape(4,3)) #### Reshaping the 2d array

arr3_flatten = arr3.flatten()
print(arr3_flatten)  ##  flatten creates a copy of the original and hence doesnt change any values in the original
arr3_flatten[2] = -1  
print(arr3)

arr3_ravel = arr3.ravel()
arr3_ravel[2] = -1   ## ravel doesn't create any copy, saves memory but does changes to the original array
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2 -1  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### np.arrange function

In [17]:
print(np.arange(0,10))  ## single 'r' in arange
print(np.arange(15,0,-1))
print(np.arange(0,10,2))

[0 1 2 3 4 5 6 7 8 9]
[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
[0 2 4 6 8]


### np.linspace    ###np.logspace

In [25]:
print(np.linspace(start=1,stop=50,num=10,dtype=int))
#####logspace is used for handling logs(not mentioned here)

[ 1  6 11 17 22 28 33 39 44 50]


### np.zeroes and  np.ones

In [24]:
arr = np.zeros([2,2])
print(arr)

arr2 = np.ones([2,2])
print(arr2)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


### np.tile and np.repeat

In [29]:
l = [1,3,5]
print(np.tile(l,2))
print(np.repeat(l,2))

[1 3 5 1 3 5]
[1 1 3 3 5 5]


### Generating random numbers

In [43]:
print(np.random.rand(2,2))  ##random function between [0,1)
print(np.random.randn(2,2)) ##clear this out yourself
print(np.random.randint(0,20,size = [3,3])) ## random numbers between specified range,[0-20) here
print(np.random.random()) ##prints one random number between (0-1]
print(np.random.random(size=[2,2])) ## of size 2*2
print(np.random.choice(['a','e','i','o','u'],size = 2)) ##randomly selects any 2 with equal probability
print(np.random.choice(['a','e','i','o','u'],size = 3,p=[0.5,0.1,0.1,0.1,0.2])) ##clearly more number of a's as probaility of a is 0.5


[[0.90663178 0.48430543]
 [0.49283511 0.10573957]]
[[-0.39786801  0.68586209]
 [-1.45933708  0.04894316]]
[[ 7  1 16]
 [ 0 15  8]
 [15 17  1]]
0.5763320838829903
[[0.13266678 0.92864167]
 [0.90011155 0.77373176]]
['u' 'e']
['a' 'a' 'u']


### seed the random numbers

In [44]:
rn = np.random.RandomState(100) ##Create the random state
print(rn.rand(2,2)) ##printing random numbers between [0,1)
np.random.seed(100) ##setting the seed
print(np.random.rand(2,2))




[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]
[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]


### getting unique items

In [47]:
# Create random integers of size 10 between [0,10)
np.random.seed(100)
arr_rand = np.random.randint(0, 10, size=10)
print(arr_rand)

uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : ", uniqs)
print("Counts : ", counts)


[8 8 3 7 7 0 4 2 5 2]
Unique items :  [0 2 3 4 5 7 8]
Counts :  [1 2 1 1 1 2 2]
